version: "1.27"

services:

  backstage-app:
    container_name: backstage-app
    build:
      dockerfile: Dockerfile
      context: ./backstage-app
    environment:
      - EXT_BASE_URL=${BACKSTAGE_EXT_BASE_URL}
      - INT_BASE_URL=${BACKSTAGE_INT_BASE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - 7007:7007
