version: "1.27"

services:

  backstage-app:
    container_name: backstage-app
    build:
      dockerfile: Dockerfile
      context: ./backstage-app
    environment:
      - APP_CONFIG_app_baseUrl=${BACKSTAGE_BASE_URL}
      - APP_CONFIG_backend_baseUrl=${BACKSTAGE_BASE_URL}
      - APP_CONFIG_cors_origin=${BACKSTAGE_BASE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - 7007:7007
