version: "1.27"

services:

  backstage-app:
    container_name: backstage-app
    build:
      dockerfile: packages/backend/Dockerfile
      context: ./backstage-app
    environment:
      - BASE_URL=${BACKSTAGE_BASE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 7007:7007
