version: "1.27"

services:

  db:
    image: postgres:15.1
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  db-admin:
    container_name: db-admin
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
