name: Build Backstage App Docker Image 

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Build docker image
        uses: docker/build-push-action@v3
        working-directory: ./backstage-app
        with:
          push: false
          tags: jm89/backstage-app-play:latest